require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TracksController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Track. As you add validations to Track, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {title: "Potato", track_number: 1, length_in_seconds: 420}
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TracksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all tracks as @tracks" do
      track = Track.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:tracks)).to eq([track])
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Track" do
        expect {
          post :create, {:track => valid_attributes}, valid_session
        }.to change(Track, :count).by(1)
      end

      it "assigns a newly created track as @track" do
        post :create, {:track => valid_attributes}, valid_session
        expect(assigns(:track)).to be_a(Track)
        expect(assigns(:track)).to be_persisted
      end

      it "returns an empty response" do
        post :create, {:track => valid_attributes}, valid_session
        expect(response.status).to eq(204)
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {title: "Mango", track_number: 2}
      }

      it "updates the requested track" do
        track = Track.create! valid_attributes
        put :update, {:id => track.to_param, :track => new_attributes}, valid_session
        track.reload
        expect(track.title).to eq("Mango")
        expect(track.track_number).to eq(2)
      end

      it "assigns the requested track as @track" do
        track = Track.create! valid_attributes
        put :update, {:id => track.to_param, :track => valid_attributes}, valid_session
        expect(assigns(:track)).to eq(track)
      end

      it "returns an empty response" do
        track = Track.create! valid_attributes
        put :update, {:id => track.to_param, :track => valid_attributes}, valid_session
        expect(response.status).to eq(204)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested track" do
      track = Track.create! valid_attributes
      expect {
        delete :destroy, {:id => track.to_param}, valid_session
      }.to change(Track, :count).by(-1)
    end

    it "returns an empty response" do
      track = Track.create! valid_attributes
      delete :destroy, {:id => track.to_param}, valid_session
      expect(response.status).to eq(204)
    end
  end

end
